# Generated by Django 2.2.28 on 2022-06-04 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_software_technical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='introduction',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='job',
        ),
        migrations.RemoveField(
            model_name='work',
            name='descreption',
        ),
    ]
