# Generated by Django 2.2.28 on 2022-06-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20220604_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(default='description', verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='profile',
            name='introduction',
            field=models.TextField(default='INTRODUCE', verbose_name='自己紹介'),
        ),
        migrations.AddField(
            model_name='profile',
            name='job',
            field=models.TextField(default='job', verbose_name='仕事'),
        ),
        migrations.AddField(
            model_name='work',
            name='descreption',
            field=models.TextField(default='description', verbose_name='説明'),
        ),
    ]
